### ISSUE TITLE
Dart-sass >1.32.8

### ISSUE THREAD

**Issue by mrleblanc101** [waldemarfm/sass-svg-uri#4]
Dart-sass doesn't support slash as divisor anymore: https://sass-lang.com/documentation/breaking-changes/slash-div
Instead of using `math.div()`, there should be a mixin to keep compatibility with node-sass and dart-sass.
Foundation for site created an abstraction function: https://github.com/ahukkanen/foundation-sites/blob/28f0cc3252272e0c6d3e2b18d376a6beda6f766f/scss/util/_math.scss
```scss
@function divide($dividend, $divisor, $precision: 12) {
  $sign: if($dividend > 0 and $divisor > 0 or $dividend < 0 and $divisor < 0, 1, -1);
  $dividend: abs($dividend);
  $divisor: abs($divisor);
  @if $dividend == 0 {
    @return 0;
  }
  @if $divisor == 0 {
    @error "Cannot divide by 0";
  }
  $remainder: $dividend;
  $result: 0;
  $factor: 10;
  @while ($remainder > 0 and $precision >= 0) {
    $quotient: 0;
    @while ($remainder >= $divisor) {
      $remainder: $remainder - $divisor;
      $quotient: $quotient + 1;
    }
    $result: $result * 10 + $quotient;
    $factor: $factor * .1;
    $remainder: $remainder * 10;
    $precision: $precision - 1;
    @if ($precision < 0 and $remainder >= $divisor * 5) {
      $result: $result + 1;
    }
  }
  $result: $result * $factor * $sign;
  $dividend-unit: unit($dividend);
  $divisor-unit: unit($divisor);
  $unit-map: (
    "px": 1px,
    "rem": 1rem,
    "em": 1em,
    "%": 1%
  );
  @if ($dividend-unit != $divisor-unit and map-has-key($unit-map, $dividend-unit)) {
    $result: $result * map-get($unit-map, $dividend-unit);
  }

  @return $result;
}
```
